services:
  frontend:
    image: jollygoodhorsepower/timestamper
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: redis:alpine
